### ISSUE TITLE
When will implement Allure2 Features?

### ISSUE THREAD

**Issue by kncxstudio** [dailymotion/allure-go#15]
When will implement ```Allure2 Features```? Thanks for your development.

**Comment by Ubermensch01** [comment]
Hi @kncxstudio, 
Thank you for your interest in this project. We're currently working to get to feature parity with the Java bindings or close to it. Which features in particular do you need the most at the moment?

**Comment by kncxstudio** [comment]
@Ubermensch01 Thanks for your reply. `Features` and `Story` are the most needed.

**Comment by Ubermensch01** [comment]
@kncxstudio we have recently published a new release that handles **Features** and **Stories** labels - [here (v2.0)](https://github.com/dailymotion/allure-go/releases/tag/v2.0)
Here's an example of utilizing these features:
```func TestFeaturesAndLabels(t *testing.T) {
	allure.TestWithParameters(t,
		"Test with features and stories",
		nil, // this is where parameters would go
		allure.TestLabels{
			Story:   []string{"Story 1"},
			Feature: []string{"Feature 1", "Feature 2"},
		},
		func() {
                   ....
		})
}```

**Comment by kncxstudio** [comment]
@Ubermensch01 Thanks for your effort.I will try this and give you feedback.
