### ISSUE TITLE
Generate report for existing tests

### ISSUE THREAD

**Issue by aady501** [dailymotion/allure-go#36]
Could we use this plugin to generate reports without updating existing tests.
Like the python adaptor: https://github.com/allure-examples/allure-python-pytest, works without any changes in the code.

**Comment by ubermensch01** [comment]
Hi @aady501, 

Unfortunately, golang is fairly specific about unit tests doesn't presently allow plugins and custom test listeners. 
At the moment I see no way existing code can be caught and translated into metadata for allure to pick up.

Regards,
Stan.
