### ISSUE TITLE
Add testId parameter(feature request)

### ISSUE THREAD

**Issue by ShadeCat** [dailymotion/allure-go#37]
When restarting tests, separate test cases are generated for each restart. The problem can be solved by explicitly adding the test case ID to the autotest as a parameter. Is there no such possibility? Could you add it?

**Comment by ubermensch01** [comment]
Hi @ShadeCat,

I looked up the way it is done with Java adaptors, I think it is doable. most likely there will be no need to specify an ID altogether as it will be handled internally. Give me some time to produce something tangible.

And thank you for your interest in the golang adaptor!

Regards,
Stan.

**Comment by ubermensch01** [comment]
Hi @ShadeCat,

I forked this repo and created a tag v0.5.6 with the dedupe test tracking feature along with suite support, you can check it out here: https://github.com/ubermensch01/allure-go/releases/tag/v0.5.6

Regards,
Stan.

**Comment by ubermensch01** [comment]
@ShadeCat sorry for the delay, you can use v0.6.0 now.
