### ISSUE TITLE
Host label should not be used to generate testCaseId/historyId

### ISSUE THREAD

**Issue by muhmud** [dailymotion/allure-go#40]
If you use a docker host to run tests and generate `allure-results`, such as when using a Jenkins CI pipeline, you get a different value for `host` each time the CI job runs, which generates a different `testCaseId` each time. This is because the labels used to generate the ID includes `host`.

This results in the test cases becoming duplicated within Allure TestOps server. For this reason, it would be best not to include the host label when generating these IDs.

I have worked around the issue by using the `-h` parameter to fix the host name of the docker container.

**Comment by ubermensch01** [comment]
@muhmud, sorry for being a slowpoke. Linked PR should solve your problem.

**Comment by muhmud** [comment]
Hey @ubermensch01 , thanks so much, looks great to me :+1:
