### ISSUE TITLE
environment variable ALLURE_RESULTS_PATH cannot be empty

### ISSUE THREAD

**Issue by karthikeyanalaguraja** [dailymotion/allure-go#42]
I have set the env variable for this, but while running the test i am always getting this error.

== RUN   TestStep
This block of code is for allure testing
2022/02/08 15:56:55 environment variable ALLURE_RESULTS_PATH cannot be empty
2022/02/08 15:56:55 mkdir /allure-results: read-only file system Failed to create allure-results folder
2022/02/08 15:56:55 Failed to write content of result to json file Failed to write in file: open /allure-results/e01dd688-dbe6-457e-98cd-5038054a273e-result.json: no such file or directory
--- PASS: TestStep (0.00s)
PASS

**Comment by ubermensch01** [comment]
I suspect you're setting `ALLURE_RESULTS_PATH` as `/allure-results`.  Assuming you're using macOS, you don't have permissions to create a directory at `/` level of your filesystem. I suggest you specify an absolute path to the location of your choice.

**Comment by karthikeyanalaguraja** [comment]
@ubermensch01  you are correct. I have mac and i am using the relative path. But now I set to an absolute path like below, but still getting the same error. 

karthikeyanalaguraja@rmc02fg0slmd6r inventory-search-api-tests % echo $ALLURE_RESULTS_PATH
/Users/karthikeyanalaguraja/Developer/inventory-search-api-tests/allure-results
karthikeyanalaguraja@rmc02fg0slmd6r inventory-search-api-tests %

**Comment by karthikeyanalaguraja** [comment]
Thanks again for helping with this. This is the sample code i have, 

func TestStep(t *testing.T) {
	allure.Test(t, allure.Action(func() {
		fmt.Println("This block of code is for allure testing")
	}))
}

Before running the test, i do this in terminal,

karthikeyanalaguraja@RMC02FG0SLMD6R inventory-search-api-tests % echo $ALLURE_RESULTS_PATH
/Users/karthikeyanalaguraja/Developer/inventory-search-api-tests/allure-results
karthikeyanalaguraja@RMC02FG0SLMD6R inventory-search-api-tests % 

But when I run my test I am getting this error 

GOROOT=/usr/local/Cellar/go/1.17.5/libexec #gosetup
GOPATH=/Users/karthikeyanalaguraja/go #gosetup
/usr/local/Cellar/go/1.17.5/libexec/bin/go test -c -o /private/var/folders/6z/dt39y7y97zv1ngft5h0zbkfh0000gq/T/GoLand/___TestStep_in_gitlab_vroom_com_vroom_quality_assurance_inventory_search_api_tests_test.test gitlab.vroom.com/vroom-quality-assurance/inventory-search-api-tests/test #gosetup
/usr/local/Cellar/go/1.17.5/libexec/bin/go tool test2json -t /private/var/folders/6z/dt39y7y97zv1ngft5h0zbkfh0000gq/T/GoLand/___TestStep_in_gitlab_vroom_com_vroom_quality_assurance_inventory_search_api_tests_test.test -test.v -test.paniconexit0 -test.run ^\QTestStep\E$
env: qa
=== RUN   TestStep
This block of code is for allure testing
2022/02/09 09:55:36 mkdir /Users/karthikeyanalaguraja/Developer/inventory-search-api-tests/allure-results/allure-results: no such file or directory Failed to create allure-results folder
2022/02/09 09:55:36 Failed to write content of result to json file Failed to write in file: open /Users/karthikeyanalaguraja/Developer/inventory-search-api-tests/allure-results/allure-results/e43cead1-5763-40d5-a279-835bfc941756-result.json: no such file or directory
--- PASS: TestStep (0.00s)
PASS

Process finished with the exit code 0

**Comment by ubermensch01** [comment]
@karthikeyanalaguraja I think I see what is causing this.
You're setting an environment variable in a terminal session, but you're running the tests through GoLand; that's why you're getting an error in GoLand run output.

To resolve this, you have to edit the `Go Test` run configuration template in GoLand. You should add your environment variable to an 'Environment' field. Here's a screenshot for more context:
![Screen Shot 2022-02-09 at 21 43 05](https://user-images.githubusercontent.com/1215522/153327150-47d82886-d53a-4a49-a545-9119bacfde40.png)

I suggest you either specify the root of the project folder to have your test results in one place or specify `./`, which will create the `allure-results` folder wherever you run your tests.
