### ISSUE TITLE
How to generate Allure-report 

### ISSUE THREAD

**Issue by karthikeyanalaguraja** [dailymotion/allure-go#44]
In Node, I will be using the npm run allure:report. How to do this with allure GO. I got allure-results but am not sure how to generate an allure report.

![image](https://user-images.githubusercontent.com/52118452/153437700-bb0009a7-2f14-4aed-a449-9fe48890bd1f.png)

Please help

**Comment by ubermensch01** [comment]
Hi @karthikeyanalaguraja, `allure-go` is a library that enables the generation of interim test report data that you see in the `allure-results` folder, the npm package you are referring to is a utility that generates a static HTML report based on the interim data; please refer to the instructions on commandline utility installation [here](https://docs.qameta.io/allure/#_installing_a_commandline).

**Comment by karthikeyanalaguraja** [comment]
Thank you, this resolve this issue
