### ISSUE TITLE
Allure not found

### ISSUE THREAD

**Issue by karthikeyanalaguraja** [dailymotion/allure-go#49]
I was able to generate the allure results and allure report locally. But i am using git lab and there i am trying to run this command with docker image 

 allure generate allure-results --clean -o allure-report

but getting the below error,
$ allure generate allure-results --clean -o allure-report
/scripts-975-835204/step_script: line 181: allure: command not found

But i understand we need  allure-commandline which is installed locally using npm. But the docker image i have is related to golang. Is there an golang version of allure-commandline ?

please help

**Comment by MaximeBellou** [comment]
Sorry for the very long delay in the answer.
I understand your docker image is related to Golang, but the allure command line doesn't care about that.
You need your Golang image to embed the allure binary (=custom Dockerfile) or to use another allure docker image with shared volumes to generate the reports.
